server:
  port: 8080
spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/springcloud?characterEncoding=utf-8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456

mybatis:
  type-aliases-package: git.gaozhanghappy.model
  mapper-locations: classpath:mapper/*.xml
